version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: nasa-mongodb-prod
    environment:
      MONGO_INITDB_DATABASE: nasa
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_prod:/data/db
    networks:
      - nasa-network-prod
    restart: always

  server:
    build:
      context: ./server
      target: production
    container_name: nasa-server-prod
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongodb:27017/nasa
      - SESSION_SECRET=${SESSION_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
    networks:
      - nasa-network-prod
    restart: always

  client:
    build:
      context: ./client
      target: production
    container_name: nasa-client-prod
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - '80:80'
    depends_on:
      - server
    networks:
      - nasa-network-prod
    restart: always

networks:
  nasa-network-prod:
    driver: bridge

volumes:
  mongodb_data_prod:
