version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: nasa-mongodb
    environment:
      MONGO_INITDB_DATABASE: nasa
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - nasa-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nasa-server
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongodb:27017/nasa
      - SESSION_SECRET=your-session-secret
      - FRONTEND_URL=http://localhost:3000
    ports:
      - '8000:8000'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    networks:
      - nasa-network
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nasa-client
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    networks:
      - nasa-network
    stdin_open: true
    tty: true
    restart: unless-stopped

networks:
  nasa-network:
    driver: bridge

volumes:
  mongodb_data:
